# Testes local:

# POST http://localhost:7071/api/Products

# {
#     "product": {
#         "Reference": "ABC123",
#         "Desc": "Prod 1",
#         "Price": 100,
#         "Category": "Feminino"
#     }
# }

# PUT http://localhost:7071/api/Products

# {
#     "product": {
#         "id": "21c3c4ab-fe31-47f8-9f3c-6e30e7d0d8f9",
#         "Reference": "DEF456",
#         "Desc": "Produto 1",
#         "Price": 180,
#         "Category": "Masculino"
#     }
# }

# DELETE http://localhost:7071/api/Products

# {
#     "product": {
#         "id": "21c3c4ab-fe31-47f8-9f3c-6e30e7d0d8f9",
#         "Reference": "DEF456",
#         "Desc": "Produto 1",
#         "Price": 180,
#         "Category": "Masculino"
#     }
# }

# GET http://localhost:7071/api/GetProductById

# {
#     "id": "21c3c4ab-fe31-47f8-9f3c-6e30e7d0d8f9",
#     "partitionKey": "Masculino"
# }

# GET http://localhost:7071/api/GetProductsByCategory

# {
#     "partitionKey": "Masculino"
# }

# Testes Azure:

# POST https://ecommerceapppostech.azurewebsites.net/api/Products?

# {
#     "product": {
#         "Reference": "TESTE123",
#         "Desc": "Prod 123",
#         "Price": 123,
#         "Category": "Masc"
#     }
# }

# PUT https://ecommerceapppostech.azurewebsites.net/api/Products?

# {
#     "product": {
#         "id": "91e96f0a-f143-4d49-8336-44486b0526d6",
#         "Reference": "tst123",
#         "Desc": "Prod123update",
#         "Price": 12345,
#         "Category": "Masc"
#     }
# }

# DELETE https://ecommerceapppostech.azurewebsites.net/api/Products?

# {
#     "product": {
#         "id": "91e96f0a-f143-4d49-8336-44486b0526d6",
#         "Reference": "tst123",
#         "Desc": "Prod123update",
#         "Price": 12345,
#         "Category": "Masc"
#     }
# }

# GET https://ecommerceapppostech.azurewebsites.net/api/GetProductById

# {
#     "id": "91e96f0a-f143-4d49-8336-44486b0526d6",
#     "partitionKey": "Masc"
# }

# GET https://ecommerceapppostech.azurewebsites.net/api/GetProductsByCategory

# {
#     "partitionKey": "Masculino"
# }