POST http://localhost:7071/api/Products

{
    "product": {
        "Reference": "",
        "Desc": "",
        "Price": ,
        "Category": ""
    }
}

PUT http://localhost:7071/api/Products

{
    "product": {
        "Reference": "",
        "Desc": "",
        "Price": ,
        "Category": ""
    }
}

